version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/chatapp?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres_data:
